### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by sandeepchathala** [sandeepchathala/SElab23_team9#5]
Dashboard of the Program Committee members should contain the following features :
- [ ] #6 - To display the user details
- [ ] #8 - To display all the assigned papers
- [ ] #9 - To display all the unassigned papers
- [ ] #37 - To display all the accepted papers
- [ ] #38 - To display all the rejected papers
![image](https://github.com/sandeepchathala/SElab23_team9/assets/156419640/dda4d3fc-d1b2-41b8-bb8d-4ad2d1a88182)
